config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # need to be securize later (only available for admin)
  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => 'administration/sidekiq'
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    confirmations: 'admins/confirmations',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    unlocks: 'admins/unlocks'
  }
  devise_for :users, path: '', path_names: { edit: '/account' }, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  get '/cart', to: 'cart#show'
  resources :items, only: %i[index show]
  resources :cart_items, only: %i[create update destroy]
  namespace 'administration' do
    resources :items, except: %i[show destroy] do
      member do
        post :update_sales_status
        patch :update_sales_status
        put :update_sales_status
      end
    end
    resources :carts
  end
  resources :charges # Stripe
end

app/controllers/administration/carts_controller.rb
# frozen_string_literal: true

module Administration
  class CartsController < AdministrationController
    before_action :authenticate_admin!

    def index
      @carts = Cart.all.where(status: %i[paid processed])
    end

    def show
      @cart = Cart.find(params[:id])
      @items = @cart.cart_items
    end

    def update
      @cart = Cart.find(params[:id])
      if @cart.paid?
        @cart.update(status: :processed)
        @cart.save
        flash[:notice] = "Commande mise à jour comme traitée"
      else # @cart.processed?
        @cart.update(status: :paid)
        flash[:notice] = "Commande mise à jour comme non traitée"
      end
      redirect_to administration_carts_path
    end

    def destroy
      @cart = Cart.find(params[:id])
      @cart.destroy
      flash[:notice] = "Commande supprimée"
      redirect_to administration_carts_path
    end
  end
end

app/controllers/administration/items_controller.rb
# frozen_string_literal: true

module Administration
  class ItemsController < AdministrationController
    before_action :authenticate_admin!

    def index
      @items = Item.all.where(on_sale: 1)
    end

    def new
      @item = Item.new
    end

    def create
      @item = Item.new(item_parameters)
      @item.save
      if @item.save
        flash[:notice] = "Nouvel article créé"
      else
        flash[:alert] = "Vous devez au moins renseigner un titre et un prix"
      end
      redirect_to administration_items_path
    end

    def edit
      @item = Item.find(params[:id])
    end

    def update
      @item = Item.find(params[:id])
      @item.update(item_parameters)
      if @item.save
        flash[:notice] = "L'article a bien été édité"
      else
        flash[:alert] = "Vous devez au moins renseigner un titre et un prix"
      end
      redirect_to administration_items_path
    end

    def update_sales_status
      @item = Item.find(params[:id])
      @item.update(on_sale: 0)
      flash[:notice] = "L'article n'est plus en vente"
      redirect_to administration_items_path
    end

    def show
      @item = Item.find(params[:id])
    end

    private

    def item_parameters
      params.require(:item).permit(
        :image_url,
        :title,
        :description,
        :original_price
      )
    end
  end
end

app/controllers/administration_controller.rb
# frozen_string_literal: true

class AdministrationController < ApplicationController
  layout "administration"
end

app/views/layouts/administration/_flash_messages.html.erb
<% if notice %>
	<div class='alert alert-success p-2'>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger p-2'>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/administration/_navbar.html.erb
<% if admin_signed_in? %>

<div class="wrapper">
  <div class="d-flex">
    <nav class="sidebar">
      <div class="sidebar-content">

        <p class="sidebar-brand">
          <i class="align-middle" data-feather="box"></i>
          <span class="align-middle">ADMIN</span>
        </p>

        <ul class="sidebar-nav">
          <li class="sidebar-header">
            <%= current_admin.email %>
          </li>
          <li class="sidebar-item">
            <a href="<%= administration_carts_path %>" class="sidebar-link">
              <i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Mes commandes</span>
              <!-- <span class="sidebar-badge badge badge-primary">6</span> -->
            </a>
          </li>
          <li class="sidebar-item">
            <a href="<%= administration_items_path %>" class="sidebar-link">
              <i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Mes produits</span>
            </a>
          </li>
          <li class="sidebar-item">
            <%= link_to "Se déconnecter", destroy_admin_session_path, method: :delete, class: "sidebar-link" %>
          </li>
        </ul>

      </div>
    </nav>

<% end %>