config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # need to be securize later (only available for admin)
  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => 'administration/sidekiq'
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    confirmations: 'admins/confirmations',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    unlocks: 'admins/unlocks'
  }
  devise_for :users, path: '', path_names: { edit: '/account' }, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  get '/cart', to: 'cart#show'
  resources :items, only: %i[index show]
  resources :cart_items, only: %i[create update destroy]
  namespace 'administration' do
    resources :items, except: %i[show destroy] do
      member do
        post :update_sales_status
        patch :update_sales_status
        put :update_sales_status
      end
    end
    resources :carts
  end
  resources :charges # Stripe
end

app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id                  :bigint(8)        not null, primary key
#  title               :string           not null
#  description         :text
#  original_price      :decimal(, )
#  has_discount        :boolean          default(FALSE)
#  on_sale             :boolean          default(TRUE)
#  image_url           :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  discount_percentage :integer          default(0)
#

class Item < ApplicationRecord
  validates :title, presence: true

  has_many :cart_items, dependent: :destroy
  has_many :item_orders, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :orders, through: :item_orders
  has_one_attached :picture
end

app/controllers/administration/carts_controller.rb
# frozen_string_literal: true

module Administration
  class CartsController < AdministrationController
    before_action :authenticate_admin!

    def index
      @carts = Cart.all.where(status: %i[paid processed])
    end

    def show
      @cart = Cart.find(params[:id])
      @items = @cart.cart_items
    end

    def update
      @cart = Cart.find(params[:id])
      if @cart.paid?
        @cart.update(status: :processed)
        @cart.save
        flash[:notice] = "Commande mise à jour comme traitée"
      else # @cart.processed?
        @cart.update(status: :paid)
        flash[:notice] = "Commande mise à jour comme non traitée"
      end
      redirect_to administration_carts_path
    end

    def destroy
      @cart = Cart.find(params[:id])
      @cart.destroy
      flash[:notice] = "Commande supprimée"
      redirect_to administration_carts_path
    end
  end
end

app/controllers/administration/items_controller.rb
# frozen_string_literal: true

module Administration
  class ItemsController < AdministrationController
    before_action :authenticate_admin!

    def index
      @items = Item.all.where(on_sale: 1)
    end

    def new
      @item = Item.new
    end

    def create
      @item = Item.new(item_parameters)
      @item.save
      if @item.save
        flash[:notice] = "Nouvel article créé"
      else
        flash[:alert] = "Vous devez au moins renseigner un titre et un prix"
      end
      redirect_to administration_items_path
    end

    def edit
      @item = Item.find(params[:id])
    end

    def update
      @item = Item.find(params[:id])
      @item.update(item_parameters)
      if @item.save
        flash[:notice] = "L'article a bien été édité"
      else
        flash[:alert] = "Vous devez au moins renseigner un titre et un prix"
      end
      redirect_to administration_items_path
    end

    def update_sales_status
      @item = Item.find(params[:id])
      @item.update(on_sale: 0)
      flash[:notice] = "L'article n'est plus en vente"
      redirect_to administration_items_path
    end

    def show
      @item = Item.find(params[:id])
    end

    private

    def item_parameters
      params.require(:item).permit(
        :image_url,
        :title,
        :description,
        :original_price
      )
    end
  end
end

app/controllers/administration_controller.rb
# frozen_string_literal: true

class AdministrationController < ApplicationController
  layout "administration"
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = Item.all.where(on_sale: true)
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/views/administration/items/edit.html.erb
<main class="content">
  <div class="container-fluid p-0">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h1 class="card-title mb-0">Produit n°<%= @item.id %> : <%= @item.title %></h1>
          </div>
          <div class="card-body">
            <div id="introduction">
              <%=  form_for [:administration, @item] do |f| %>

                <b><%= f.label :'Nom du produit' %></b><br>
                <%= f.text_field :title %><br><br>

                <b><%= f.label :"Url de l'image" %></b><br>
                <%= f.text_field :image_url %><br><br>

                <b><%= f.label :'Description du produit' %></b><br>
                <%= f.text_area :description %><br><br>

                <b><%= f.label :'Prix' %></b><br>
                <%= f.number_field :original_price, class: "text_field", step: 0.01 %><br><br><br>
                <%= f.submit "Enregistrer", class: "btn btn-primary" %>
                <%= link_to "Voir en tant qu'acheteur", item_path(@item.id), class: "btn btn-secondary", target: :_blank %>
                <%= link_to "Retirer ce produit de la vente", update_sales_status_administration_item_path(@item.id), method: :update_sales_status, class: "btn btn-danger" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/administration/items/index.html.erb
<main class="content">
  <div class="container-fluid p-0">
    <div class="clearfix">
      <form class="form-inline float-right mt--1 d-none d-md-flex">
        <a href="<%= new_administration_item_path %>" class="btn btn-primary"><i class="align-middle" data-feather="plus"></i>Nouveau produit</a>
      </form>
      <h1 class="h3 mb-3">Mes produits</h1>
    </div>

    <div class="row">
      <div class="col-12">
        <div class="card flex-fill">
          <table class="table table-striped my-0">
            <thead>
              <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prix</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @items.each do |item| %>
                <tr>
                  <td><%= item.id %></td>
                  <td><%= item.title %></td>
                  <td><%= number_to_currency(item.original_price) %></td>
                  <td><%= link_to "Editer", edit_administration_item_path(item.id) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/administration/items/new.html.erb
<main class="content">
  <div class="container-fluid p-0">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h1 class="card-title mb-0">Nouveau produit</h1>
          </div>
          <div class="card-body">
            <div id="introduction">
              <%=  form_for @item, url: {action: "create"} do |f| %>

                <b><%= f.label :'Nom du produit' %></b><br>
                <%= f.text_field :title %><br><br>

                <b><%= f.label :"Url de l'image" %></b><br>
                <%= f.text_field :image_url %><br><br>

                <b><%= f.label :'Description du produit' %></b><br>
                <%= f.text_area :description %><br><br>

                <b><%= f.label :'Prix' %></b><br>
                <%= f.number_field :original_price, class: "text_field", step: 0.01 %><br><br><br>

                <%= f.submit "Créer", class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>