config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # need to be securize later (only available for admin)
  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => 'administration/sidekiq'
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    confirmations: 'admins/confirmations',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    unlocks: 'admins/unlocks'
  }
  devise_for :users, path: '', path_names: { edit: '/account' }, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    unlocks: 'users/unlocks'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  get '/cart', to: 'cart#show'
  resources :items, only: %i[index show]
  resources :cart_items, only: %i[create update destroy]
  namespace 'administration' do
    resources :items, except: %i[show destroy] do
      member do
        post :update_sales_status
        patch :update_sales_status
        put :update_sales_status
      end
    end
    resources :carts
  end
  resources :charges # Stripe
end

app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id                  :bigint(8)        not null, primary key
#  title               :string           not null
#  description         :text
#  original_price      :decimal(, )
#  has_discount        :boolean          default(FALSE)
#  on_sale             :boolean          default(TRUE)
#  image_url           :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  discount_percentage :integer          default(0)
#

class Item < ApplicationRecord
  validates :title, presence: true

  has_many :cart_items, dependent: :destroy
  has_many :item_orders, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :orders, through: :item_orders
  has_one_attached :picture
end

app/controllers/administration/items_controller.rb
# frozen_string_literal: true

module Administration
  class ItemsController < AdministrationController
    before_action :authenticate_admin!

    def index
      @items = Item.all.where(on_sale: 1)
    end

    def new
      @item = Item.new
    end

    def create
      @item = Item.new(item_parameters)
      @item.save
      if @item.save
        flash[:notice] = "Nouvel article créé"
      else
        flash[:alert] = "Vous devez au moins renseigner un titre et un prix"
      end
      redirect_to administration_items_path
    end

    def edit
      @item = Item.find(params[:id])
    end

    def update
      @item = Item.find(params[:id])
      @item.update(item_parameters)
      if @item.save
        flash[:notice] = "L'article a bien été édité"
      else
        flash[:alert] = "Vous devez au moins renseigner un titre et un prix"
      end
      redirect_to administration_items_path
    end

    def update_sales_status
      @item = Item.find(params[:id])
      @item.update(on_sale: 0)
      flash[:notice] = "L'article n'est plus en vente"
      redirect_to administration_items_path
    end

    def show
      @item = Item.find(params[:id])
    end

    private

    def item_parameters
      params.require(:item).permit(
        :image_url,
        :title,
        :description,
        :original_price
      )
    end
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = Item.all.where(on_sale: true)
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/views/items/index.html.erb
<div class="fadein">
  <div class="container">

    <div class="row">

      <div class="col-lg-12">
      	<center>
        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="https://da4pli3l5vc0d.cloudfront.net/43/f7/43f75382a344173c26d105e1d4e25d0b3b9743cb" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="https://i.pinimg.com/originals/99/0f/3d/990f3dc7ddc51c9ab86228aefb8ffdb1.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="https://www.sacredwall.com/wp-content/uploads/2016/07/pokemon-900x350.jpg" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        </center>
        <br>

        <div class="row">
          <% @items.each do |item| %>
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <%= link_to image_tag(item.image_url, class: "card-img-top"), item_path(item.id) %>
                <div class="card-body">
                  <h4 class="card-title">
                    <%= link_to item.title, item_path(item.id), class: "card-link" %>
                  </h4>
                  <h5><%= number_to_currency(item.original_price) %></h5>
                  <p class="card-text"><%= item.description %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>

      </div>

    </div>

  </div>
</div>

app/views/items/show.html.erb
<div class="fadein">
<div class="container" id="container_item_show">
  <div class="row">
    <div class="col-lg-4">
      <%= image_tag @item.image_url, class: "card-img-top img-fluid" %>
    </div>
    <div class="col-lg-8">
      <div class="card-body">
        <h5 class="card-title"><%= @item.title %></h5>
        <p class="card-text"><%= @item.description %></p>
        <h5 class="card-title"><%= number_to_currency(@item.original_price) %></h5><br>
        <%= button_to "Ajouter au panier", cart_items_path(:id => @item), :remote => true, class: 'btn btn-outline-primary btn-lg' %>
        <br><%= link_to "retour aux produits", items_path, class: "card-link" %>
      </div>
    </div>
  </div>
</div><br>
</div>